[project]
name = "ty-extensions-unofficial"
version = "0.1.0.dev0"
description = "A properly packaged fork of the official ty-extensions"
readme = "README.md"
authors = [
    { name = "InSyncWithFoo", email = "insyncwithfoo@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "ty_extensions"
